################################################################################
#
# dlt-daemon
#
################################################################################

DLT_DAEMON_VERSION = 3.0.0
DLT_DAEMON_SITE = $(call github,COVESA,dlt-daemon,v$(DLT_DAEMON_VERSION))
DLT_DAEMON_LICENSE = MPL-2.0
DLT_DAEMON_LICENSE_FILES = LICENSE
DLT_DAEMON_INSTALL_STAGING = YES
DLT_DAEMON_DEPENDENCIES = host-pkgconf
DLT_DAEMON_CONF_OPTS = \
	-DCMAKE_INSTALL_SYSCONFDIR=/etc \
	-DWITH_DLT_WERROR=OFF \
	-DWITH_DLT_TESTS=OFF \
	-DWITH_DLT_UNIT_TESTS=OFF \
	-DWITH_DLT_CXX11_EXT=$(if $(filter y,$(BR2_INSTALL_LIBSTDCPP)),ON,OFF) \
	-DWITH_DLT_USE_IPv6=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_IPV6)),ON,OFF) \
	-DDLT_USER=root \
	-DWITH_DLT_SYSTEM=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_SYSTEM)),ON,OFF) \
	-DWITH_DLT_ADAPTOR=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_ADAPTOR)),ON,OFF) \
	-DWITH_DLT_ADAPTOR_STDIN=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_ADAPTOR_STDIN)),ON,OFF) \
	-DWITH_DLT_ADAPTOR_UDP=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_ADAPTOR_UDP)),ON,OFF) \
	-DWITH_UDP_CONNECTION=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_UDP_CONNECTION)),ON,OFF) \
	-DWITH_DLT_FILETRANSFER=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_FILETRANSFER)),ON,OFF) \
	-DWITH_DLT_DBUS=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_DBUS)),ON,OFF) \
	-DWITH_DLT_LOGSTORAGE_GZIP=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_LOGSTORAGE_GZIP)),ON,OFF) \
	-DWITH_EXTENDED_FILTERING=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_EXTENDED_FILTERING)),ON,OFF) \
	-DWITH_SYSTEMD_WATCHDOG=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_SYSTEMD_WATCHDOG)),ON,OFF) \
	-DWITH_SYSTEMD_JOURNAL=$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_SYSTEMD_JOURNAL)),ON,OFF)

ifeq ($(BR2_PACKAGE_DLT_DAEMON_DBUS),y)
DLT_DAEMON_DEPENDENCIES += dbus
endif

ifneq ($(filter y,$(BR2_PACKAGE_DLT_DAEMON_FILETRANSFER) $(BR2_PACKAGE_DLT_DAEMON_LOGSTORAGE_GZIP)),)
DLT_DAEMON_DEPENDENCIES += zlib
endif

ifeq ($(BR2_PACKAGE_DLT_DAEMON_EXTENDED_FILTERING),y)
DLT_DAEMON_DEPENDENCIES += json-c
endif

ifeq ($(BR2_PACKAGE_DLT_DAEMON_CONSOLE),y)
DLT_DAEMON_CONF_OPTS += -DWITH_DLT_CONSOLE=ON
else
DLT_DAEMON_CONF_OPTS += -DWITH_DLT_CONSOLE=OFF
endif

ifeq ($(BR2_PACKAGE_DLT_DAEMON_EXAMPLES),y)
DLT_DAEMON_CONF_OPTS += -DWITH_DLT_EXAMPLES=ON
else
DLT_DAEMON_CONF_OPTS += -DWITH_DLT_EXAMPLES=OFF
endif

ifeq ($(BR2_PACKAGE_SYSTEMD),y)
DLT_DAEMON_DEPENDENCIES += systemd
DLT_DAEMON_CONF_OPTS += -DWITH_SYSTEMD=ON -DSYSTEMD_UNITDIR=/usr/lib/systemd/system

define DLT_DAEMON_INSTALL_INIT_SYSTEMD
	$(INSTALL) -D -m 0644 $(DLT_DAEMON_PKGDIR)/50-dlt-daemon.preset \
		$(TARGET_DIR)/usr/lib/systemd/system-preset/50-dlt-daemon.preset
	$(if $(filter y,$(BR2_PACKAGE_DLT_DAEMON_SYSTEM)), \
		$(INSTALL) -D -m 0644 $(DLT_DAEMON_PKGDIR)/50-dlt-system.preset \
			$(TARGET_DIR)/usr/lib/systemd/system-preset/50-dlt-system.preset)
endef
else
DLT_DAEMON_CONF_OPTS += -DWITH_SYSTEMD=OFF
endif

$(eval $(cmake-package))